name: architecture_linter
description: Software analytics tool that helps developers analyse and improve project architecture structure.
homepage: https://github.com/Iteo/architecture_linter
repository: https://github.com/Iteo/architecture_linter
version: 0.2.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: '>=4.1.0 <6.3.1'
  analyzer_plugin: '>=0.10.0 <0.11.4'
  args: ^2.4.2
  collection: ^1.18.0
  file: ^7.0.0
  glob: ^2.1.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  linteo: ^1.1.0
  mocktail: ^1.0.2
  test: ^1.25.0