name: architecture_linter
description: Software analytics tool that helps developers analyse and improve project architecture structure.
homepage: https://github.com/Iteo/architecture_linter
repository: https://github.com/Iteo/architecture_linter
# Remember, increase also architecture_linter version
# in tools/analyzer_plugin/pubspec.yaml to the same version
version: 0.2.2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ^6.4.1
  analyzer_plugin: ^0.11.3
  args: ^2.4.2
  collection: ^1.18.0
  file: ^7.0.0
  glob: ^2.1.2
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  linteo: ^1.1.0
  mocktail: ^1.0.2
  test: ^1.25.0